networks:
  kafka-network:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    hostname: kafka
    ports:
        - "9092:9092"
        # - "9093:9093"
    environment: # https://kafka.apache.org/documentation/#brokerconfigs_num.partitions
        
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9091
        KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
        KAFKA_LISTENERS: CONTROLLER://kafka:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

        # Required for a single node cluster
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_BROKER_ID: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

        # KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
        CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - kafka-network
 
#   kafka-ui:
#       image: provectuslabs/kafka-ui
#       container_name: kafka-ui
#       ports:
#           - "8000:8080"
#       restart: always
#       depends_on:
#           - kafka
#       environment:
#           DYNAMIC_CONFIG_ENABLED: 'true'
#           KAFKA_CLUSTERS_0_NAME: local
#           KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093

  akhq:
    container_name: akhq
    image: tchiotludo/akhq:0.25.1
    ports:
      - "8000:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "kafka:9093"
    depends_on:
      - kafka
    networks:
      - kafka-network

  postgres:
    image: postgres:14.13 
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/PostgreSQL/data:/var/lib/postgresql/data
