server:
    port: 8002

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/test
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                default_schema: kafka_test
                ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
    batch:
        jdbc:
            initialize-schema: always
        job:
            name: FirstJobTest
    
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
topics:
    orders: orders